service: Sharp-layerService

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

layers:
  Sharp:
    path: ''
    compatibleRuntimes:
      - nodejs12.x
      - nodejs14.x
    allowedAccounts:
      - '*'

resources:
  Outputs:
    SharpLayerExport:
      Value:
        Ref: SharpLambdaLayer
      Export:
        Name: SharpLambdaLayer
