service: PNGjs-layerService

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

layers:
  PNGjs:
    path: ''
    compatibleRuntimes:
      - nodejs12.x
      - nodejs14.x
    allowedAccounts:
      - '*'

resources:
  Outputs:
    PNGjsLayerExport:
      Value:
        Ref: PNGjsLambdaLayer
      Export:
        Name: PNGjsLambdaLayer
